image: Visual Studio 2017

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain nightly --default-host x86_64-pc-windows-msvc
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustup component add clippy rustfmt

build: false

test_script:
  - cargo build --release --verbose --locked
  - cargo clippy --all-targets --all-features --verbose -- -D warnings
  - cargo fmt --all --verbose -- --verbose --check
  - cargo test --release --verbose
