# Выбираем контейнер с необходимыми Rust компонентами
os: Visual Studio 2015

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain stable --default-host x86_64-pc-windows-msvc
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin

build: false

test_script:
  - cargo build --verbose
  - cargo test --verbose
