[package]
name = "nanoid"
version = "0.2.0"
authors = ["Nikolay Govorov <nikolay_govorov@bk.ru>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/nikolay-govorov/nanoid.git"
documentation = "https://docs.rs/nanoid"
homepage = "https://github.com/nikolay-govorov/nanoid"
description = """
A tiny, secure, URL-friendly, unique string ID generator for Rust.
"""
keywords = ["uuid", "random", "id", "url"]

include = ["src/**/*", "Cargo.toml", "LICENSE", "README.md", "CHANGELOG.md"]

[dependencies]
rand = "0.4.1"

[badges]
appveyor = { repository = "nikolay-govorov/nanoid", branch = "master", service = "github" }
travis-ci = { repository = "nikolay-govorov/nanoid", branch = "master" }

maintenance = { status = "actively-developed" }
